### PR TITLE
Fix compatibility with Mercurial 3.2

### PR DESCRIPTION
**Pull request by fingolfin**
This fixes issue #27.

### CODE REVIEW

**Comment by michaeljones** [comment]
I'm afraid I'm not in a place to comment on the implementation details but with the current latest from this repo I ended up in a place with this error:

```
transaction abort!
rollback completed
Traceback (most recent call last):
  File "/home/mike/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/home/mike/bin/git-remote-hg", line 1308, in main
    do_export(parser)
  File "/home/mike/bin/git-remote-hg", line 1099, in do_export
    parse_commit(parser)
  File "/home/mike/bin/git-remote-hg", line 871, in parse_commit
    node = hghex(repo.commitctx(ctx))
  File "..../local/lib/python2.7/site-packages/mercurial/localrepo.py", line 63, in wrapper
    return orig(repo.unfiltered(), *args, **kwargs)
  File "..../local/lib/python2.7/site-packages/mercurial/localrepo.py", line 1409, in commitctx
    fctx = ctx[f]
  File "..../local/lib/python2.7/site-packages/mercurial/context.py", line 66, in __getitem__
    return self.filectx(key)
  File "..../local/lib/python2.7/site-packages/mercurial/context.py", line 1674, in filectx
    return self._filectxfn(self._repo, self, path)
  File "/home/mike/bin/git-remote-hg", line 806, in getfilectx
    raise IOError
IOError
error: fast-export died of signal 13
fatal: Error while running fast-export
```

Which is awkwardly unhelpful.

And with @fingolfin changes in this pull request, it works. Thanks very much to @fingolfin as I prefer git and this error had me worried that I had to go back to mercurial.

Cheers,
Michael

**Comment by fingolfin** [comment]
Note: Please don't be fooled by the failing tests. They are failing for the parent commit, too, and are due to an incompatibility of recent hg dev versions with hg-git 0.7.0. But hg-git dev in turn introduces problems for git-remote-hg of its own, see issue #35.

**Comment by signalpillar** [comment]
This issue is till relevant - not compatible with the latest `mercurial`.
I used `mercurial==3.1` to make it work.

**Comment by fingolfin** [comment]
@signalpillar Wait, are you talking about this repos, or are you talking about my fork?

**Comment by signalpillar** [comment]
@fingolfin, I followed instructions from this repo

1) Installation step

```
wget https://raw.github.com/felipec/git-remote-hg/master/git-remote-hg -O ~/bin/git-remote-hg
chmod +x ~/bin/git-remote-hg
```

2) `mercurial` version is the latest

```
$ pip show mercurial
---
Metadata-Version: 1.1
Name: mercurial
Version: 3.4.1
Summary: Fast scalable distributed SCM (revision control, version control) system
Home-page: http://mercurial.selenic.com/
Author: Matt Mackall and many others
Author-email: mercurial@selenic.com
License: GNU GPLv2 or any later version
Location: /Users/signalpillar/.pyenv/versions/2.7.8/lib/python2.7/site-packages
Requires:
```

3) Clone demo repo 
```
$ git clone "hg::http://selenic.com/repo/hello"
Cloning into 'hello'...
warning: selenic.com certificate with fingerprint f0:40:cc:b9:46:62:b6:69:48:c5:1a:65:d0:34:35:22:b6:e0:1b:87 not verified (check hostfingerprints or web.cacerts config setting)
real URL is https://selenic.com/repo/hello
Traceback (most recent call last):
  File "/Users/signalpillar/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/Users/signalpillar/bin/git-remote-hg", line 1286, in main
    repo = get_repo(url, alias)
  File "/Users/signalpillar/bin/git-remote-hg", line 433, in get_repo
    repo.pull(peer, heads=None, force=True)
  File "/Users/signalpillar/.pyenv/versions/2.7.8/lib/python2.7/site-packages/mercurial/repoview.py", line 335, in __getattr__
    return getattr(self._unfilteredrepo, attr)
AttributeError: 'localrepository' object has no attribute 'pull'
```

4) Rollback to version `3.1` and now `clone` works.

**Comment by tboegi** [comment]
@signalpillar: Can you try the version from fingolfin:
wget https://raw.github.com/fingolfin/git-remote-hg/master/git-remote-hg
                                             ^^^^^^^

**Comment by sleep-walker** [comment]
@tboegi, I had the same problem as @signalpillar, using @fingolfin fork fixed it.

**Comment by alexei-31** [comment]
The author of this repository does not come for a long time, all of the latest patches look in the  @fingolfin repository: https://github.com/fingolfin/git-remote-hg

**Comment by alexei-31** [comment]
You can see this commit at [e716a9e1](https://github.com/fingolfin/git-remote-hg/commit/e716a9e1a9e460a45663694ba4e9e8894a8452b2) in that new fork.

**Comment by drothlis** [comment]
Note that if you use Debian or Ubuntu, the `git-remote-hg` package contains this patch.

**Pull request closed without merging**
